import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import type { PageMap } from './pagemap.ts';
import { redact } from './report.ts';
import { TEST_DATA } from '../config/test-data.ts';

/**
 * knowledge/sitemap.json (data) and knowledge/sitemap.md (what the agent reads):
 * where each page is, what is on it, and what each plan sees there. Written by
 * `npm run crawl`, one page updated in place by `npm run probe`. No ticket IDs,
 * no records (table rows, field values): pages only.
 */

export const KNOWLEDGE_DIR = path.resolve(process.cwd(), 'knowledge');

export interface SitemapPage {
  /** With `<slug>` for the restaurant, e.g. /admin/restaurants/<slug>/bookings. */
  path: string;
  area: string;
  /** YYYY-MM-DD the structure was last read. */
  checked: string;
  h1: string;
  under: string;
  headings: string[];
  tabs: Array<{ label: string; controls: string[] }>;
  tables: string[][];
  controls: string[];
  /** Plan label -> what that plan sees: open / wall: … / 403 / redirect → … , plus 🔒 or (not in sidebar). */
  access: Record<string, string>;
  /** Plan label -> Marketplace add-on states. */
  addons?: Record<string, string[]>;
}

export interface Sitemap {
  environment: string;
  crawledAt: string;
  /** Who the crawl used, per plan: "Gold: TBL Ben's Bistro". */
  sources: string[];
  structureFrom: string;
  gaps: string[];
  differs: string[];
  pages: Record<string, SitemapPage>;
}

export function today(): string {
  return new Date().toISOString().slice(0, 10);
}

/** Restaurant-specific parts of a path or text replaced by placeholders, secrets masked. */
export function generalise(text: string, restaurant?: { name: string; reference?: string }): string {
  let out = text;
  if (restaurant?.reference) {
    out = out
      .split(`/admin/restaurants/${restaurant.reference}`).join('/admin/restaurants/<slug>')
      .split(`/widget/${restaurant.reference}`).join('/widget/<slug>')
      .split(`?${restaurant.reference}`).join('?<slug>');
  }
  if (restaurant?.name && restaurant.name.length >= 3) out = out.split(restaurant.name).join('<restaurant>');
  return redact(out);
}

/** A control as one sitemap line: `selector` tag[type] "label". */
export function controlLine(c: PageMap['controls'][number]): string {
  return `\`${c.selector}\` ${c.tag}${c.type ? `[${c.type}]` : ''}${c.label ? ` "${c.label}"` : ''}`;
}

const MONTH = '(?:January|February|March|April|May|June|July|August|September|October|November|December|Jan|Feb|Mar|Apr|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec)';
const DATE = new RegExp(`(?:(?:Mon|Tues|Wednes|Thurs|Fri|Satur|Sun)day,?\\s+)?(?:${MONTH}\\s+\\d{1,2}(?:st|nd|rd|th)?,?\\s+\\d{4}|\\d{1,2}\\s+${MONTH},?\\s+\\d{4}|\\d{4}-\\d{2}-\\d{2})`, 'g');
/** Words of the test-data guest names ("Glory"): records QA created, never page structure. */
const GUEST = (() => {
  const words = [...new Set(TEST_DATA.guests.flatMap((g) => g.split(/\s+/)).filter((w) => w.length >= 4 && !/^(test|testing|qa)$/i.test(w)))];
  return words.length ? new RegExp(`\\b(?:${words.map((w) => w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')})[\\w-]*(?:\\s+test\\w*)?`, 'gi') : null;
})();

/** Dates and QA guest names replaced: they change with the data, not with the page. */
export function scrub(text: string): string {
  const dated = text.replace(DATE, '<date>');
  return GUEST ? dated.replace(GUEST, '<guest>') : dated;
}

/**
 * The page structure of a map, records left out: controls inside tables, field values,
 * card titles (H5/H6, often a guest or a review), generated ids (`-v-3`, not stable selectors).
 */
export function structureOf(map: PageMap, restaurant?: { name: string; reference?: string }): Pick<SitemapPage, 'h1' | 'under' | 'headings' | 'tables' | 'controls'> {
  const g = (t: string) => scrub(generalise(t, restaurant));
  const seen = new Set<string>();
  const controls = map.controls
    .filter((c) => !c.inTable && !/-v-\d+$/.test(c.selector))
    .map((c) => g(controlLine(c)))
    .filter((line) => !seen.has(line) && Boolean(seen.add(line)));
  const headings = map.headings.filter((h) => /^H[1-4] /.test(h)).map(g);
  return { h1: g(map.h1), under: g(map.under), headings, tables: map.tables.map((t) => t.map(g)), controls };
}

export function readSitemap(dir = KNOWLEDGE_DIR): Sitemap | null {
  const file = path.join(dir, 'sitemap.json');
  if (!existsSync(file)) return null;
  try {
    return JSON.parse(readFileSync(file, 'utf8')) as Sitemap;
  } catch {
    return null;
  }
}

export function renderSitemap(map: Sitemap): string {
  const lines = [
    '# Tableo sitemap',
    '',
    'Generated by `npm run crawl` and kept current by `npm run probe`: do not edit by hand, re-crawl instead.',
    'Where things are and what each plan sees. Expected entitlements by plan: `plans.md`; behaviour and quirks: `app.md`.',
    'Paths use `<slug>` for the restaurant. Access: open · wall (the app\'s upgrade text) · HTTP status · 🔒 locked in the',
    'sidebar · (not in sidebar) = reached by URL only. Navigation help only: the ticket wins, the app is the evidence.',
    '',
    `Crawled: ${map.environment}, ${map.crawledAt.slice(0, 10)} · Administrator in ${map.sources.join('; ') || 'none'} · structure from ${map.structureFrom}`,
  ];
  if (map.gaps.length) lines.push(`Not crawled: ${map.gaps.join('; ')}`);
  lines.push('');
  if (map.differs.length) {
    lines.push('## Differs from the pricing page (worth a look, not a verdict)', '', ...map.differs.map((d) => `- ${d}`), '');
  }
  const pages = Object.values(map.pages).sort((a, b) => a.area.localeCompare(b.area) || a.path.localeCompare(b.path));
  for (const p of pages) {
    const access = Object.entries(p.access).map(([plan, state]) => `${plan}: ${state}`).join(' · ');
    lines.push(`## ${p.area} — \`${p.path}\``, '', `Checked ${p.checked}${access ? ` · ${access}` : ''}`);
    if (p.h1) lines.push(`H1 "${p.h1}"${p.under ? ` — under it: "${p.under}"` : ''}`);
    if (p.headings.length) lines.push(`Headings: ${p.headings.join(' | ')}`);
    for (const headers of p.tables) if (headers.length) lines.push(`Table: ${headers.join(' | ')}`);
    for (const [plan, states] of Object.entries(p.addons ?? {})) if (states.length) lines.push(`Add-ons (${plan}): ${states.join(' | ')}`);
    if (p.controls.length) lines.push('Controls:', ...p.controls.map((c) => `- ${c}`));
    for (const tab of p.tabs) {
      lines.push(`Tab "${tab.label}":`, ...(tab.controls.length ? tab.controls.map((c) => `- ${c}`) : ['- (no controls)']));
    }
    lines.push('');
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

export function writeSitemap(map: Sitemap, dir = KNOWLEDGE_DIR): string {
  mkdirSync(dir, { recursive: true });
  writeFileSync(path.join(dir, 'sitemap.json'), `${JSON.stringify(map, null, 2)}\n`, 'utf8');
  const file = path.join(dir, 'sitemap.md');
  writeFileSync(file, renderSitemap(map), 'utf8');
  return file;
}

/**
 * Probe's write-back: one page's structure replaced, its access for this plan set,
 * other plans' access kept. Creates the sitemap when there is none yet.
 */
export function updateSitemapPage(
  entry: Omit<SitemapPage, 'access' | 'checked' | 'tabs' | 'area'> & { area?: string; tabs?: SitemapPage['tabs'] },
  environment: string,
  plan?: { label: string; access: string },
  dir = KNOWLEDGE_DIR,
): string {
  const map: Sitemap = readSitemap(dir) ?? {
    environment,
    crawledAt: new Date().toISOString(),
    sources: [],
    structureFrom: 'probe',
    gaps: ['no crawl yet: npm run crawl'],
    differs: [],
    pages: {},
  };
  const previous = map.pages[entry.path];
  map.pages[entry.path] = {
    ...entry,
    area: entry.area ?? previous?.area ?? 'Probed',
    tabs: entry.tabs?.length ? entry.tabs : previous?.tabs ?? [],
    checked: today(),
    access: { ...(previous?.access ?? {}), ...(plan ? { [plan.label]: plan.access } : {}) },
    ...(previous?.addons ? { addons: previous.addons } : {}),
  };
  return writeSitemap(map, dir);
}
